<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS01_Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient>tvh.mai.us@gmail.com;</mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>047f0e3e-86e3-470e-a273-ec96b75f0295</testSuiteGuid>
   <testCaseLink>
      <guid>b3631d52-afb5-4088-adc9-25cffa43e021</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC01_LoginSuccess</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1dd13c7d-2e27-4c9e-88ee-f519e5a7b822</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>992500dc-1919-44a7-b984-c5dd618e08cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2991f3d8-f200-4422-8237-2418de42e17b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>965e0d97-c773-4e06-b7d9-41ddc49464d3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f555fa3-9d8f-468b-9961-22f17b6d4b71</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6b47e9e2-6585-4aa1-ab6e-5ac9a5c7c002</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC03_LoginWrongPass</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8965767-7e63-47fd-892c-aef1c65bb18f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4bee574f-c5bd-4470-b35a-a900cbb21dc7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>89c3ff51-b276-43eb-b61b-7110851c1309</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c513bbda-37fa-4fea-b558-c97650567e43</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>919096cc-63b4-4a66-95c9-0daf30089c28</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>da67f472-0a0f-4197-ba96-8e62ffaf149f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC02_LoginWrongUser</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fde1edbc-7f16-4525-a886-30b3c08df74b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d9f2b0a-2489-4555-bccf-4ac85deda8c7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>552e47ef-fe1a-4346-bb92-02ccdcafbf44</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d160a375-b48e-4aaa-9963-3fa5339ffe49</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c36dbe54-b946-40a2-963d-2eb8d951121b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>30b58ef6-6b38-45f7-8294-bf8f9a55c33d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC04_LoginFaile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>164d27f9-049a-4726-b962-f340de238a0e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4c7f12a-0a7b-4847-82fc-093d7559b113</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6ed9b42-d30d-4148-9ddc-dfe998065bbb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>229c4c13-d3e2-4a63-a8f2-3c9e579ad2d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>099a3514-c990-4312-9d36-f3e8abd1e998</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>979a6bb4-812a-4ef2-9c5b-dd1a7d75e0d4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC05_LoginBlankUser</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a25145b-28b2-419a-aaf2-51a8eca71e62</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94161a3a-6dea-49c7-b213-41d5b0927f4c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>557dd2b6-7521-4e97-b626-98e9d725e0c1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4533d66b-1643-4f68-8dd0-1191d2c7d627</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0b8700c6-3789-4465-8bcf-8d842e6a9ad4</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
